# Generated by Django 5.2.3 on 2025-06-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo (.mp4)')], default='image', max_length=10)),
                ('media_file', models.FileField(help_text='Image (.jpg, .png) ou vidéo (.mp4)', upload_to='hero/')),
                ('primary_button_label', models.CharField(blank=True, max_length=100)),
                ('primary_button_url', models.URLField(blank=True)),
                ('secondary_button_label', models.CharField(blank=True, max_length=100)),
                ('secondary_button_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prenom'),
        ),
    ]
