# Generated by Django 5.2.3 on 2025-06-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_herobanner_alter_customuser_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('button_label', models.CharField(blank=True, max_length=100)),
                ('button_url', models.URLField(blank=True)),
                ('image_1', models.ImageField(upload_to='features/')),
                ('image_2', models.ImageField(upload_to='features/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
