# Generated by Django 5.2.3 on 2025-06-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_featuresection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='menus/')),
                ('category', models.CharField(choices=[('special', 'Spécial semaine'), ('event', 'Événementiel'), ('classic', 'Classique'), ('kids', 'Enfant'), ('veggie', 'Végétarien')], default='classic', max_length=20)),
                ('available_days', models.JSONField(help_text="Liste des jours disponibles ex: ['monday', 'friday']")),
                ('is_new', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
