# Generated by Django 5.2.3 on 2025-06-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
    ]
