# Generated by Django 5.2.3 on 2025-06-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChefOfTheWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chefs/')),
                ('bio', models.TextField()),
                ('specialties', models.TextField(help_text='Liste séparée par des virgules')),
                ('quote', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
