# Generated by Django 5.2.3 on 2025-06-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_chefoftheweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('button_label', models.CharField(default='Découvrir', max_length=100)),
                ('button_url', models.URLField()),
                ('image', models.ImageField(upload_to='about/')),
                ('image_alt', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
